name: CI
env:
  HAPPO_API_KEY: ${{secrets.HAPPO_API_KEY}}
  HAPPO_API_SECRET: ${{secrets.HAPPO_API_SECRET}}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies 📦
        #Using npm ci is generally faster than running npm install
        run: |
          cd dev-portfolio
          npm ci
      - name: Build the app 🏗
        run: |
          cd dev-portfolio
          npm run build
      - name: Run component tests 🔸
        run: |
          cd dev-portfolio
          npm run test:jest
      - name: Start the app 📤
        run: |
          cd dev-portfolio
          npm start &
          npx wait-on --timeout 60000
      - name: Run visual tests
        run: |
          cd dev-portfolio
          npm run test:visual
